# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyAdmin' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for EasyAdmin
  rn_path = '../node_modules/react-native'
  
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"  
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  target 'EasyAdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyAdmin-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for EasyAdmin-tvOS

  target 'EasyAdmin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
